// Governance & Records + Person & Service Quality — content + quiz banks.

export const governanceQuality = [
  {
    slug: "record-keeping-and-documentation",
    description: "Keeping accurate, timely and confidential records that support safe care and meet CQC requirements.",
    blocks: [
      { type: "slide", title: "Record keeping", body: "Good records are essential for safe, joined-up care and are a legal and CQC requirement.\n\nBy the end you will be able to:\n• Explain why records matter\n• Write clear, factual records\n• Keep records confidential and secure\n• Avoid common recording mistakes" },
      { type: "slide", title: "Why records matter", body: "Records:\n\n• Provide a clear account of the care given\n• Help the whole team give consistent, safe care\n• Support continuity when staff change\n• Evidence what happened if there is a concern or complaint\n\n'If it isn't recorded, it didn't happen' — records protect the person and you." },
      { type: "slide", title: "Good recording", body: "Records should be:\n\n• Factual — what you saw and did, not opinions or assumptions\n• Clear and legible; written in plain language\n• Timely — completed as soon as possible after the event\n• Signed and dated\n• Free of jargon, abbreviations and gaps\n\nNever alter a record to hide a mistake — draw a single line through errors, initial, and correct them." },
      { type: "slide", title: "Confidentiality and security", body: "Care records contain sensitive personal data.\n\n• Only share on a need-to-know basis\n• Store paper records securely; lock away when not in use\n• Keep digital records password-protected; don't share logins\n• Never leave records where others can read them\n• Don't discuss or photograph records on personal devices\n\nData protection law (UK GDPR) applies to all care records." },
      { type: "mcq", question: "A good care record should be:", options: ["Based on your opinion", "Factual, clear, timely, signed and dated", "Vague to save time", "Written days later"], answer_index: 1 },
      { type: "fill_gap", text: "Records should state the facts, not opinions or ___.", answers: ["assumptions", "assumption"] },
      { type: "drag_drop", prompt: "Match the quality to the practice.", pairs: [{ item: "Factual", match: "What you saw and did" }, { item: "Timely", match: "As soon as possible" }, { item: "Secure", match: "Locked away / password" }, { item: "Correcting", match: "Single line, initial" }] },
      { type: "slide", title: "Summary", body: "• Records give a clear account of care and are a legal/CQC requirement.\n• Write factual, clear, timely records — signed and dated, no gaps or jargon.\n• Never alter records to hide mistakes; correct properly.\n• Keep records confidential and secure under UK GDPR.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Care records should be:", options: ["Opinion-based", "Factual, clear and timely", "Written weeks later", "Kept vague"], answer_index: 1 },
      { question: "'If it isn't recorded...'", options: ["...it doesn't matter", "...it didn't happen", "...it's fine", "...tell no one"], answer_index: 1 },
      { question: "To correct a written error you should:", options: ["Scribble it out", "Draw a single line, initial and correct it", "Use correction fluid", "Rewrite the page secretly"], answer_index: 1 },
      { question: "Records should be shared:", options: ["Freely", "On a need-to-know basis", "On social media", "With anyone"], answer_index: 1 },
      { question: "Records must be:", options: ["Anonymous", "Signed and dated", "Unsigned", "In pencil"], answer_index: 1 },
      { question: "Digital records should be:", options: ["Shared logins", "Password-protected", "Left open", "Public"], answer_index: 1 },
      { question: "Good records support:", options: ["Confusion", "Continuity and safe care", "Secrecy", "Nothing"], answer_index: 1 },
      { question: "Which law applies to care records?", options: ["UK GDPR / Data Protection", "COSHH", "Fire Safety Order", "RIDDOR"], answer_index: 0 },
      { question: "Records should be written:", options: ["Days later", "As soon as possible after the event", "Only weekly", "Never"], answer_index: 1 },
      { question: "Altering a record to hide a mistake is:", options: ["Acceptable", "Falsification and never allowed", "Efficient", "Required"], answer_index: 1 },
      { question: "Jargon and abbreviations in records:", options: ["Are best practice", "Should be avoided for clarity", "Save time safely", "Are required"], answer_index: 1 },
      { question: "Paper records should be:", options: ["Left on the side", "Stored securely / locked away", "Photographed on your phone", "Shared openly"], answer_index: 1 },
    ],
  },

  {
    slug: "information-governance-and-gdpr",
    description: "Handling personal data lawfully and securely under UK GDPR and the Data Protection Act 2018.",
    blocks: [
      { type: "slide", title: "Information governance", body: "Information governance is how organisations handle personal information safely, legally and appropriately.\n\nBy the end you will be able to:\n• Understand UK GDPR principles\n• Recognise personal and special-category data\n• Keep information secure\n• Respond to a data breach or a person's request" },
      { type: "slide", title: "The data protection principles", body: "Under UK GDPR, personal data must be:\n\n• Used lawfully, fairly and transparently\n• Collected for specified purposes only\n• Adequate and limited to what's needed\n• Accurate and kept up to date\n• Kept no longer than necessary\n• Kept secure\n\nHealth information is 'special category' data and needs extra protection." },
      { type: "slide", title: "Keeping information secure", body: "Protect information every day:\n\n• Share only on a need-to-know basis\n• Lock devices and log out; never share passwords\n• Don't discuss people in public or on personal social media\n• Send information by secure means; check the recipient\n• Store paper securely and dispose of it by shredding\n\nCurtains, screens and quiet conversations protect privacy too." },
      { type: "slide", title: "Breaches and people's rights", body: "A data breach is any loss, theft or wrongful sharing of personal data (e.g. a lost phone, an email to the wrong person).\n\n• Report a breach to your manager / DPO immediately — serious breaches must be reported to the ICO within 72 hours\n\nPeople have rights, including the right to see their data (a 'subject access request') and to have inaccurate data corrected. Pass any such request to your manager." },
      { type: "mcq", question: "You email a client's care notes to the wrong person. This is:", options: ["Nothing to worry about", "A data breach to report immediately", "Fine if you apologise", "Only a problem if noticed"], answer_index: 1 },
      { type: "fill_gap", text: "Personal data should only be shared on a ___-to-know basis.", answers: ["need"] },
      { type: "drag_drop", prompt: "Match the principle to the practice.", pairs: [{ item: "Kept secure", match: "Lock devices" }, { item: "Accurate", match: "Keep up to date" }, { item: "Minimised", match: "Only what's needed" }, { item: "Purpose", match: "Use for a stated reason" }] },
      { type: "slide", title: "Summary", body: "• UK GDPR requires personal data to be used lawfully, minimally, accurately and securely.\n• Health data is special-category — protect it carefully.\n• Share on a need-to-know basis; secure devices, records and conversations.\n• Report breaches immediately (ICO within 72 hours for serious ones); pass on subject access requests.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Under UK GDPR, personal data must be kept:", options: ["Forever", "No longer than necessary", "Public", "Unsecured"], answer_index: 1 },
      { question: "Health information is:", options: ["Not personal", "Special-category data needing extra protection", "Public", "Unimportant"], answer_index: 1 },
      { question: "Emailing care notes to the wrong person is:", options: ["Fine", "A data breach", "Good practice", "Efficient"], answer_index: 1 },
      { question: "Personal data should be shared:", options: ["Freely", "On a need-to-know basis", "On social media", "With anyone"], answer_index: 1 },
      { question: "Serious data breaches must be reported to the ICO within:", options: ["72 hours", "1 month", "1 year", "Never"], answer_index: 0 },
      { question: "A subject access request lets a person:", options: ["Change staff", "See the data held about them", "Get free care", "Nothing"], answer_index: 1 },
      { question: "Passwords should be:", options: ["Shared", "Kept private and not shared", "Written on the wall", "Simple and public"], answer_index: 1 },
      { question: "Personal data should be:", options: ["Inaccurate", "Accurate and up to date", "Guessed", "Ignored"], answer_index: 1 },
      { question: "Disposing of paper records is done by:", options: ["Recycling openly", "Shredding securely", "Binning normally", "Leaving them out"], answer_index: 1 },
      { question: "Discussing clients on personal social media is:", options: ["Allowed", "A breach of confidentiality", "Encouraged", "Fine without names"], answer_index: 1 },
      { question: "Report a data breach to:", options: ["No one", "Your manager / DPO immediately", "The client's neighbour", "Social media"], answer_index: 1 },
      { question: "Data minimisation means collecting:", options: ["Everything possible", "Only what is needed", "Nothing", "Random data"], answer_index: 1 },
    ],
  },

  {
    slug: "conflict-resolution",
    description: "Preventing and safely de-escalating conflict and challenging behaviour in care settings.",
    blocks: [
      { type: "slide", title: "Conflict resolution", body: "Conflict can arise in care — from frustration, fear, pain or confusion. Handling it calmly keeps everyone safe.\n\nBy the end you will be able to:\n• Recognise triggers and warning signs\n• Use de-escalation techniques\n• Keep yourself and others safe\n• Report and learn from incidents" },
      { type: "slide", title: "Understanding triggers", body: "Challenging behaviour is often communication of an unmet need. Triggers include:\n\n• Pain, illness or medication effects\n• Fear, confusion or dementia\n• Loss of control or dignity\n• Noise, crowding or being rushed\n\nUnderstanding the cause helps you prevent and defuse conflict." },
      { type: "slide", title: "De-escalation", body: "To de-escalate:\n\n• Stay calm and speak softly and slowly\n• Keep a safe distance and non-threatening body language\n• Listen and acknowledge how the person feels\n• Give them space, time and choices\n• Avoid arguing, commanding or 'winning'\n• Remove triggers where you can\n\nYour calm response often calms the situation." },
      { type: "slide", title: "Staying safe and reporting", body: "If a situation escalates:\n\n• Keep between yourself and the exit; don't get cornered\n• Call for help; leave and get to safety if needed\n• Never respond with aggression or physical force except as a last resort to protect from harm, within policy and training\n• Call 999 if in danger\n\nAfterwards, record and report the incident so triggers can be understood and prevented." },
      { type: "mcq", question: "When de-escalating a situation you should:", options: ["Raise your voice", "Stay calm, listen and give space", "Argue to win", "Corner the person"], answer_index: 1 },
      { type: "fill_gap", text: "Challenging behaviour is often the communication of an unmet ___.", answers: ["need"] },
      { type: "drag_drop", prompt: "Match the technique to the goal.", pairs: [{ item: "Speak calmly", match: "Reduce tension" }, { item: "Give choices", match: "Restore control" }, { item: "Safe distance", match: "Stay safe" }, { item: "Record after", match: "Prevent recurrence" }] },
      { type: "slide", title: "Summary", body: "• Conflict often stems from unmet needs, pain, fear or confusion.\n• Prevent it by understanding triggers.\n• De-escalate with calm voice, listening, space, time and choices.\n• Keep yourself safe, call for help if needed, and report incidents to learn from them.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Challenging behaviour often communicates:", options: ["Nothing", "An unmet need", "Aggression only", "Boredom"], answer_index: 1 },
      { question: "A good de-escalation technique is:", options: ["Shouting", "Staying calm and listening", "Cornering the person", "Arguing"], answer_index: 1 },
      { question: "A common trigger for conflict is:", options: ["Calm surroundings", "Pain, fear or confusion", "Good communication", "Choice"], answer_index: 1 },
      { question: "During conflict you should keep:", options: ["Yourself cornered", "Between yourself and the exit", "The door locked", "Quiet and hidden"], answer_index: 1 },
      { question: "Giving a person choices helps restore their:", options: ["Confusion", "Sense of control", "Fear", "Pain"], answer_index: 1 },
      { question: "Physical intervention should be:", options: ["A first response", "A last resort within policy and training", "Routine", "Never recorded"], answer_index: 1 },
      { question: "After an incident you should:", options: ["Forget it", "Record and report it", "Blame the person", "Hide it"], answer_index: 1 },
      { question: "Your body language during conflict should be:", options: ["Threatening", "Calm and non-threatening", "Aggressive", "Ignoring"], answer_index: 1 },
      { question: "If you are in danger you should:", options: ["Stay and fight", "Get to safety and call 999", "Do nothing", "Argue"], answer_index: 1 },
      { question: "Understanding triggers helps you:", options: ["Provoke conflict", "Prevent and defuse conflict", "Ignore people", "Rush care"], answer_index: 1 },
      { question: "Speaking to an agitated person, you should:", options: ["Command them", "Speak softly and acknowledge their feelings", "Talk fast", "Threaten them"], answer_index: 1 },
      { question: "Reporting an incident helps to:", options: ["Blame staff", "Understand and prevent triggers", "Waste time", "Hide problems"], answer_index: 1 },
    ],
  },

  {
    slug: "complaints-handling",
    description: "Receiving and responding to complaints positively, and using them to improve the service.",
    blocks: [
      { type: "slide", title: "Complaints handling", body: "Complaints are a valuable way to improve care. Handling them well maintains trust.\n\nBy the end you will be able to:\n• See complaints positively\n• Respond appropriately when someone complains\n• Follow the complaints procedure\n• Understand people's right to complain" },
      { type: "slide", title: "Why complaints matter", body: "A complaint is any expression of dissatisfaction. They matter because they:\n\n• Show where care can improve\n• Help put things right for the person\n• Prevent small issues becoming serious\n• Are a legal right — every provider must have an accessible complaints procedure\n\nView complaints as feedback, not failure." },
      { type: "slide", title: "Responding well", body: "When someone complains:\n\n• Listen fully and stay calm — don't take it personally or become defensive\n• Acknowledge their feelings and apologise for their experience\n• Don't argue, blame others, or promise outcomes you can't control\n• Tell them how the complaint will be handled\n• Record it accurately and pass it to your manager the same day" },
      { type: "slide", title: "The complaints procedure", body: "Every organisation has a complaints procedure that people can access easily.\n\n• Complaints can be made by the person, a relative or an advocate\n• They should be acknowledged and investigated fairly, and the person kept informed\n• If unhappy with the outcome, people can escalate — for example to the Local Government & Social Care Ombudsman\n\nNo one should be treated less well for making a complaint." },
      { type: "mcq", question: "When someone makes a complaint you should:", options: ["Argue and defend yourself", "Listen, apologise for their experience, record and report it", "Ignore it", "Blame a colleague"], answer_index: 1 },
      { type: "fill_gap", text: "A complaint should be passed to your manager the same ___.", answers: ["day"] },
      { type: "drag_drop", prompt: "Match the step to the action.", pairs: [{ item: "Someone complains", match: "Listen calmly" }, { item: "They feel upset", match: "Acknowledge and apologise" }, { item: "Recording", match: "Note the facts" }, { item: "Escalation", match: "Ombudsman" }] },
      { type: "slide", title: "Summary", body: "• Complaints are feedback that helps improve care — a legal right.\n• Respond by listening, apologising for the experience, and staying calm.\n• Don't argue or blame; record accurately and report the same day.\n• Follow the complaints procedure; no one should be treated worse for complaining.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "A complaint should be seen as:", options: ["A personal attack", "Feedback to improve the service", "Something to ignore", "The client's fault"], answer_index: 1 },
      { question: "When responding to a complaint you should:", options: ["Argue", "Listen and apologise for their experience", "Blame others", "Walk away"], answer_index: 1 },
      { question: "A complaint should be passed to your manager:", options: ["Next month", "The same day", "Never", "Only if serious"], answer_index: 1 },
      { question: "Every provider must have:", options: ["No process", "An accessible complaints procedure", "A hidden process", "A verbal-only rule"], answer_index: 1 },
      { question: "You should NOT:", options: ["Listen", "Record the facts", "Promise an outcome you can't control", "Stay calm"], answer_index: 2 },
      { question: "A complaint can be made by:", options: ["Only the person", "The person, a relative or an advocate", "Only staff", "No one"], answer_index: 1 },
      { question: "If unhappy with the outcome, people can escalate to:", options: ["The Ombudsman", "The bank", "The fire service", "No one"], answer_index: 0 },
      { question: "Someone who complains should be:", options: ["Treated worse", "Treated no differently and with respect", "Ignored", "Removed"], answer_index: 1 },
      { question: "A complaint is:", options: ["Only a formal letter", "Any expression of dissatisfaction", "Always minor", "Never valid"], answer_index: 1 },
      { question: "Handling complaints well maintains:", options: ["Secrecy", "Trust", "Conflict", "Nothing"], answer_index: 1 },
      { question: "Recording a complaint should capture:", options: ["Your opinion", "The facts of the concern", "Nothing", "Blame"], answer_index: 1 },
      { question: "Small issues, if ignored, can:", options: ["Disappear always", "Become serious problems", "Improve care", "Do nothing"], answer_index: 1 },
    ],
  },
];
