// Health & Safety — detailed module content + quiz banks.

export const healthSafety = [
  {
    slug: "health-and-safety",
    description: "Your health and safety responsibilities under the Health and Safety at Work Act, risk assessment and safe working.",
    blocks: [
      { type: "slide", title: "Health & safety at work", body: "Health and safety protects you, the people you support and others from harm.\n\nBy the end you will be able to:\n• State the main legal duties\n• Understand risk assessment\n• Work safely and report hazards\n• Know what to do in an emergency" },
      { type: "slide", title: "The law and your duties", body: "The Health and Safety at Work etc. Act 1974 places duties on everyone.\n\nYour employer must provide a safe workplace, equipment, training and policies.\n\nYou must:\n• Take reasonable care of your own and others' safety\n• Follow training and safe procedures\n• Use equipment correctly\n• Report hazards, accidents and near misses" },
      { type: "slide", title: "Risk assessment", body: "A risk assessment identifies hazards and controls them. The five steps are:\n\n1. Identify the hazards\n2. Decide who might be harmed and how\n3. Evaluate the risks and decide on controls\n4. Record the findings\n5. Review and update regularly\n\nA hazard is something that could cause harm; risk is the chance it will." },
      { type: "slide", title: "Hazards and reporting", body: "Common hazards in care include slips and trips, moving and handling, infection, hazardous substances, and lone working.\n\nIf you spot a hazard:\n• Make it safe if you can do so safely\n• Report it promptly\n• Record it\n\nNear misses (no harm this time) must also be reported so problems are fixed before someone is hurt." },
      { type: "mcq", question: "The difference between a hazard and a risk is:", options: ["They are the same", "A hazard could cause harm; risk is the chance it will", "A risk is a person", "A hazard is always fatal"], answer_index: 1 },
      { type: "fill_gap", text: "A near miss should be ___ even though no one was harmed.", answers: ["reported"] },
      { type: "drag_drop", prompt: "Order the risk-assessment steps (match step to action).", pairs: [{ item: "Step 1", match: "Identify hazards" }, { item: "Step 2", match: "Decide who's harmed" }, { item: "Step 3", match: "Control the risk" }, { item: "Step 5", match: "Review" }] },
      { type: "slide", title: "Summary", body: "• Health and safety protects everyone and is a shared legal duty.\n• Take care of yourself and others; follow training; use equipment correctly.\n• Risk assessment has five steps — identify, assess, control, record, review.\n• Report hazards, accidents AND near misses.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Which law is the main health and safety legislation?", options: ["Health and Safety at Work etc. Act 1974", "Equality Act 2010", "Care Act 2014", "Data Protection Act"], answer_index: 0 },
      { question: "A hazard is:", options: ["The chance of harm", "Something that could cause harm", "A person", "A control measure"], answer_index: 1 },
      { question: "Risk is:", options: ["Something that could cause harm", "The likelihood harm will occur", "Always low", "A hazard"], answer_index: 1 },
      { question: "As a worker you must:", options: ["Ignore hazards", "Take reasonable care and follow safe procedures", "Skip training", "Use equipment however you like"], answer_index: 1 },
      { question: "A near miss should be:", options: ["Ignored", "Reported", "Kept secret", "Repeated"], answer_index: 1 },
      { question: "How many steps are in the standard risk assessment?", options: ["Two", "Five", "Ten", "Twenty"], answer_index: 1 },
      { question: "The first step of a risk assessment is:", options: ["Review", "Identify the hazards", "Record", "Buy equipment"], answer_index: 1 },
      { question: "If you spot a hazard you should:", options: ["Leave it", "Make it safe if you can and report it", "Hide it", "Wait for it to cause harm"], answer_index: 1 },
      { question: "Your employer must provide:", options: ["Nothing", "A safe workplace, training and equipment", "Only wages", "Only uniforms"], answer_index: 1 },
      { question: "Risk assessments should be:", options: ["Done once and forgotten", "Reviewed and updated regularly", "Kept secret", "Optional"], answer_index: 1 },
      { question: "A common hazard in care is:", options: ["Moving and handling", "Sunshine", "Music", "Colours"], answer_index: 0 },
      { question: "Following safe procedures protects:", options: ["Only you", "You, the people you support and others", "No one", "Only managers"], answer_index: 1 },
    ],
  },

  {
    slug: "fire-safety",
    description: "Preventing fire, understanding the fire triangle, and knowing what to do if a fire breaks out.",
    blocks: [
      { type: "slide", title: "Fire safety", body: "Fire can spread in minutes. Knowing how to prevent it and respond saves lives.\n\nBy the end you will be able to:\n• Understand what causes fire\n• Reduce fire risks\n• Respond correctly if a fire starts\n• Support people to evacuate safely" },
      { type: "slide", title: "The fire triangle", body: "Fire needs three things — the 'fire triangle':\n\n• Heat (a source of ignition)\n• Fuel (something to burn)\n• Oxygen (in the air)\n\nRemove any one and the fire cannot burn. Fire prevention is about keeping these three apart." },
      { type: "slide", title: "Preventing fire", body: "Reduce risk by:\n\n• Keeping exits and corridors clear\n• Not overloading sockets or leaving cooking unattended\n• Storing flammable materials safely\n• Reporting faulty equipment and worn wiring\n• Never blocking or wedging fire doors open\n\nEmollient creams and oxygen therapy increase fire risk — take extra care with smoking." },
      { type: "slide", title: "If a fire starts", body: "If you discover a fire:\n\n1. Raise the alarm\n2. Call 999\n3. Help people evacuate if it is safe to do so\n4. Use the nearest safe exit; do NOT use lifts\n5. Close doors behind you to slow the spread\n6. Go to the assembly point and do a head count\n\nDo NOT tackle a fire unless it is tiny and you are trained — your safety comes first." },
      { type: "mcq", question: "The three parts of the fire triangle are:", options: ["Heat, fuel, oxygen", "Water, wind, wood", "Smoke, heat, alarm", "Fuel, water, oxygen"], answer_index: 0 },
      { type: "fill_gap", text: "In a fire, you should never use the ___ to evacuate.", answers: ["lift", "lifts", "elevator"] },
      { type: "drag_drop", prompt: "Match the action to when it applies.", pairs: [{ item: "Discover a fire", match: "Raise the alarm" }, { item: "Evacuating", match: "Use stairs, not lifts" }, { item: "Leaving a room", match: "Close the door" }, { item: "Outside", match: "Head count at assembly point" }] },
      { type: "slide", title: "Summary", body: "• Fire needs heat, fuel and oxygen — remove one to stop it.\n• Prevent fire: clear exits, safe electrics, never wedge fire doors.\n• If fire starts: raise the alarm, call 999, evacuate safely, use stairs not lifts, close doors.\n• Only tackle a fire if tiny and you're trained; your safety comes first.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "The fire triangle consists of:", options: ["Heat, fuel and oxygen", "Smoke, ash and heat", "Water, wind and fuel", "Alarm, exit and extinguisher"], answer_index: 0 },
      { question: "Removing one part of the fire triangle:", options: ["Makes fire worse", "Stops the fire", "Has no effect", "Adds oxygen"], answer_index: 1 },
      { question: "In a fire you should:", options: ["Use the lift", "Use the stairs / nearest safe exit", "Hide", "Collect belongings first"], answer_index: 1 },
      { question: "When you discover a fire, first:", options: ["Investigate it", "Raise the alarm", "Finish your task", "Take a photo"], answer_index: 1 },
      { question: "Fire doors should be:", options: ["Wedged open", "Kept closed / never wedged open", "Removed", "Painted"], answer_index: 1 },
      { question: "You should call:", options: ["101", "999", "111", "No one"], answer_index: 1 },
      { question: "Closing doors as you leave:", options: ["Speeds the fire", "Slows the fire's spread", "Does nothing", "Wastes time"], answer_index: 1 },
      { question: "You should tackle a fire yourself:", options: ["Always", "Only if tiny and you're trained, and safe to do so", "Never mind safety", "With water on any fire"], answer_index: 1 },
      { question: "After evacuating you should:", options: ["Go home", "Go to the assembly point for a head count", "Re-enter for belongings", "Wander off"], answer_index: 1 },
      { question: "Oxygen therapy in the home:", options: ["Reduces fire risk", "Increases fire risk", "Has no effect", "Puts out fires"], answer_index: 1 },
      { question: "Overloading sockets:", options: ["Is safe", "Is a fire risk", "Saves energy", "Is required"], answer_index: 1 },
      { question: "Keeping corridors and exits clear:", options: ["Is unnecessary", "Supports safe evacuation", "Blocks escape", "Is optional"], answer_index: 1 },
    ],
  },

  {
    slug: "coshh",
    description: "Working safely with hazardous substances under the Control of Substances Hazardous to Health regulations.",
    blocks: [
      { type: "slide", title: "What is COSHH?", body: "COSHH — the Control of Substances Hazardous to Health Regulations 2002 — requires employers to control substances that can harm health.\n\nBy the end you will be able to:\n• Recognise hazardous substances\n• Understand hazard symbols\n• Use, store and dispose of substances safely\n• Respond to a spill or exposure" },
      { type: "slide", title: "Hazardous substances in care", body: "In care settings these include:\n\n• Cleaning products and disinfectants\n• Bleach and descalers\n• Clinical waste and bodily fluids\n• Some medicines\n• Dust and fumes\n\nHazardous substances can harm through skin contact, breathing in, swallowing or entering the eyes." },
      { type: "slide", title: "Labels and safe use", body: "Hazard symbols (orange/black or red diamond) warn you — for example corrosive, toxic, irritant or flammable.\n\nUse substances safely:\n• Read the label and the COSHH assessment before use\n• Wear the PPE provided (gloves, apron, eye protection)\n• Never mix chemicals (e.g. bleach and other cleaners release toxic gas)\n• Store in original, labelled containers, away from food and out of reach" },
      { type: "slide", title: "Spills and exposure", body: "If a substance is spilled or you're exposed:\n\n• Follow the COSHH assessment and product safety data\n• Ventilate the area and clean up using the right method and PPE\n• Skin contact — rinse with water; eyes — flush with water and seek help\n• Swallowed / serious exposure — seek medical help; call 999 if serious\n\nReport the incident." },
      { type: "mcq", question: "You should never mix bleach with other cleaning products because:", options: ["It saves money", "It can release toxic gas", "It cleans better", "It smells nice"], answer_index: 1 },
      { type: "fill_gap", text: "Hazardous substances should be stored in their original, ___ containers.", answers: ["labelled", "labeled"] },
      { type: "drag_drop", prompt: "Match the action to the safe practice.", pairs: [{ item: "Before use", match: "Read the label / COSHH sheet" }, { item: "During use", match: "Wear PPE" }, { item: "Storage", match: "Original labelled container" }, { item: "After a spill", match: "Ventilate and report" }] },
      { type: "slide", title: "Summary", body: "• COSHH controls substances hazardous to health.\n• Cleaning products, bodily fluids and some medicines are hazardous.\n• Read labels/assessments, wear PPE, never mix chemicals, store safely.\n• Deal with spills using the right method and PPE, then report.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "COSHH stands for the Control of Substances Hazardous to:", options: ["Homes", "Health", "Heating", "Hygiene"], answer_index: 1 },
      { question: "Which is a hazardous substance in care?", options: ["Bleach", "A pillow", "A chair", "A curtain"], answer_index: 0 },
      { question: "You should never mix bleach with other cleaners because:", options: ["It's expensive", "It can release toxic gas", "It's illegal to buy", "It fades colours"], answer_index: 1 },
      { question: "Before using a substance you should:", options: ["Guess", "Read the label and COSHH assessment", "Mix it with water", "Ignore the label"], answer_index: 1 },
      { question: "PPE for cleaning may include:", options: ["Gloves and apron", "A hat only", "Nothing", "Headphones"], answer_index: 0 },
      { question: "Hazardous substances should be stored:", options: ["With food", "In original labelled containers, out of reach", "In drink bottles", "Anywhere"], answer_index: 1 },
      { question: "Substances can enter the body by:", options: ["Only swallowing", "Skin, breathing, swallowing or the eyes", "Only the eyes", "They can't"], answer_index: 1 },
      { question: "A hazard symbol warns you a product is:", options: ["Safe", "Potentially harmful (e.g. corrosive/toxic)", "Free", "Food"], answer_index: 1 },
      { question: "If a chemical splashes in the eyes you should:", options: ["Rub them", "Flush with water and seek help", "Ignore it", "Wait"], answer_index: 1 },
      { question: "After a spill you should:", options: ["Leave it", "Clean it safely, ventilate and report it", "Cover it up", "Add more chemical"], answer_index: 1 },
      { question: "Decanting cleaning fluid into an unlabelled bottle is:", options: ["Good practice", "Dangerous and against COSHH", "Required", "Safe"], answer_index: 1 },
      { question: "COSHH is the responsibility of:", options: ["Only the employer", "Employer to control and staff to follow safely", "Only staff", "No one"], answer_index: 1 },
    ],
  },

  {
    slug: "slips-trips-and-falls",
    description: "Preventing slips, trips and falls — a leading cause of injury — for both staff and the people you support.",
    blocks: [
      { type: "slide", title: "Slips, trips and falls", body: "Slips, trips and falls are one of the most common causes of injury in care.\n\nBy the end you will be able to:\n• Identify common causes\n• Reduce hazards in the home\n• Support people at risk of falling\n• Respond correctly if someone falls" },
      { type: "slide", title: "Common causes", body: "Typical hazards include:\n\n• Wet or highly polished floors\n• Trailing cables and clutter\n• Loose rugs and mats\n• Poor lighting\n• Unsuitable footwear\n• Trip hazards on stairs\n\nFor the people you support, add: dizziness, medication effects, poor eyesight and reduced mobility." },
      { type: "slide", title: "Reducing the risk", body: "Prevent slips, trips and falls by:\n\n• Cleaning up spills straight away and using wet-floor signs\n• Keeping walkways clear of clutter and cables\n• Ensuring good lighting\n• Encouraging suitable footwear\n• Making sure walking aids are within reach and used correctly\n• Following the person's falls risk assessment and care plan" },
      { type: "slide", title: "If someone falls", body: "If a person falls:\n\n• Do NOT rush to lift them — you could cause injury\n• Check for injury and their response\n• Reassure them and keep them comfortable and warm\n• Call for help / 999 if injured or you're unsure\n• Only move them using the agreed safe method / equipment\n• Record and report the fall" },
      { type: "mcq", question: "If a client falls, your first action should be to:", options: ["Lift them quickly", "Check for injury and get help before moving them", "Leave them", "Continue your visit"], answer_index: 1 },
      { type: "fill_gap", text: "Spills should be cleaned up ___ to prevent slips.", answers: ["immediately", "straight away", "straightaway"] },
      { type: "drag_drop", prompt: "Match the hazard to the control.", pairs: [{ item: "Wet floor", match: "Clean up / wet-floor sign" }, { item: "Trailing cables", match: "Tidy them away" }, { item: "Poor lighting", match: "Improve lighting" }, { item: "Loose rug", match: "Remove or secure it" }] },
      { type: "slide", title: "Summary", body: "• Slips, trips and falls are a leading cause of injury.\n• Common causes: wet floors, clutter, cables, poor lighting, unsuitable footwear.\n• Reduce risk by keeping areas clear, lit and dry, and following falls care plans.\n• If someone falls, don't rush to lift — check, reassure, get help, then record and report.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Slips, trips and falls are:", options: ["Rare in care", "A leading cause of injury", "Never serious", "Not preventable"], answer_index: 1 },
      { question: "A common trip hazard is:", options: ["A tidy floor", "Trailing cables and clutter", "Good lighting", "Suitable footwear"], answer_index: 1 },
      { question: "If a person falls, you should first:", options: ["Lift them immediately", "Check for injury and get help", "Ignore it", "Leave the home"], answer_index: 1 },
      { question: "Spills should be:", options: ["Left to dry", "Cleaned up immediately", "Ignored", "Walked around"], answer_index: 1 },
      { question: "To reduce falls you should:", options: ["Dim the lights", "Keep walkways clear and well lit", "Add clutter", "Remove walking aids"], answer_index: 1 },
      { question: "After a fall you should:", options: ["Say nothing", "Record and report it", "Hide it", "Forget it"], answer_index: 1 },
      { question: "Loose rugs should be:", options: ["Left in place", "Removed or secured", "Piled up", "Ignored"], answer_index: 1 },
      { question: "A person's falls care plan should be:", options: ["Ignored", "Followed", "Hidden", "Optional"], answer_index: 1 },
      { question: "Moving a fallen person should be done:", options: ["Any way that's quick", "Using the agreed safe method / equipment", "By dragging", "By one carer always"], answer_index: 1 },
      { question: "Unsuitable footwear can:", options: ["Prevent falls", "Increase the risk of slips", "Improve grip always", "Have no effect"], answer_index: 1 },
      { question: "For the people you support, extra fall risks include:", options: ["Dizziness and medication effects", "Being well-rested", "Good eyesight", "Strong mobility"], answer_index: 0 },
      { question: "Wet-floor signs are used to:", options: ["Decorate", "Warn people of a slip hazard", "Block exits", "Nothing"], answer_index: 1 },
    ],
  },

  {
    slug: "lone-working",
    description: "Staying safe when working alone in the community, managing risks and raising the alarm.",
    blocks: [
      { type: "slide", title: "Lone working", body: "Home care staff often work alone, without direct supervision or immediate help nearby.\n\nBy the end you will be able to:\n• Recognise lone-working risks\n• Take steps to stay safe\n• Use check-in and alarm systems\n• Respond to a threatening situation" },
      { type: "slide", title: "The risks", body: "Lone-working risks include:\n\n• Accidents or illness with no one to help\n• Aggression or violence from clients, family or the public\n• Travel and driving hazards\n• Unsafe home environments (pets, hazards, poor lighting)\n\nYour employer must assess these risks and put safety measures in place." },
      { type: "slide", title: "Staying safe", body: "Protect yourself by:\n\n• Following your rota and lone-working policy\n• Keeping your phone charged and to hand\n• Using check-in/check-out systems so someone knows your whereabouts\n• Parking in well-lit areas and being aware of exits\n• Trusting your instincts — if you feel unsafe, leave\n• Reporting concerns about a client's environment" },
      { type: "slide", title: "If you feel unsafe", body: "If a situation feels threatening:\n\n• Stay calm and keep between the person and the exit\n• Do not argue or 'win' — de-escalate\n• Leave the situation and get to safety\n• Raise the alarm using your device / call for help\n• Call 999 if you are in danger\n• Report and record what happened so it can be prevented next time" },
      { type: "mcq", question: "If you feel unsafe during a lone visit, you should:", options: ["Stay and argue", "Leave and get to safety, then raise the alarm", "Ignore the feeling", "Continue as normal"], answer_index: 1 },
      { type: "fill_gap", text: "Check-in systems let others know your ___ during lone visits.", answers: ["whereabouts", "location"] },
      { type: "drag_drop", prompt: "Match the measure to the risk it reduces.", pairs: [{ item: "Charged phone", match: "Getting help" }, { item: "Check-in system", match: "Knowing your location" }, { item: "Well-lit parking", match: "Personal safety" }, { item: "Report hazards", match: "Unsafe environment" }] },
      { type: "slide", title: "Summary", body: "• Lone workers face risks with no immediate help nearby.\n• Follow your policy, keep your phone charged, and use check-in systems.\n• Trust your instincts — if you feel unsafe, leave.\n• De-escalate, get to safety, raise the alarm, and report incidents.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Lone working means:", options: ["Working with a partner", "Working without direct supervision or immediate help", "Working in an office", "Never working"], answer_index: 1 },
      { question: "A key lone-working safety tool is:", options: ["A charged phone", "A heavy bag", "Loud music", "None"], answer_index: 0 },
      { question: "Check-in/check-out systems help by:", options: ["Wasting time", "Letting others know your whereabouts", "Slowing visits", "Nothing"], answer_index: 1 },
      { question: "If you feel unsafe you should:", options: ["Stay and argue", "Leave and get to safety", "Ignore it", "Provoke the person"], answer_index: 1 },
      { question: "In danger, you should call:", options: ["111", "999", "101", "No one"], answer_index: 1 },
      { question: "Your employer must:", options: ["Ignore lone-working risks", "Assess the risks and provide safety measures", "Leave you unsupported", "Do nothing"], answer_index: 1 },
      { question: "When de-escalating you should:", options: ["Win the argument", "Stay calm and avoid confrontation", "Shout", "Block the exit for yourself"], answer_index: 1 },
      { question: "After an incident you should:", options: ["Say nothing", "Report and record it", "Hide it", "Blame yourself"], answer_index: 1 },
      { question: "Trusting your instincts means:", options: ["Ignoring warning signs", "Acting if something feels unsafe", "Taking risks", "Staying regardless"], answer_index: 1 },
      { question: "Parking for a lone visit is safest:", options: ["In dark areas", "In well-lit areas with clear exits", "Blocking driveways", "Anywhere"], answer_index: 1 },
      { question: "An unsafe home environment should be:", options: ["Ignored", "Reported", "Kept secret", "Made worse"], answer_index: 1 },
      { question: "During a threatening situation, keep:", options: ["Yourself trapped", "Between yourself and the exit clear", "The door locked", "Calm and confrontational"], answer_index: 1 },
    ],
  },

  {
    slug: "accident-and-incident-reporting",
    description: "Recording and reporting accidents, incidents and near misses accurately and promptly, including RIDDOR.",
    blocks: [
      { type: "slide", title: "Accident & incident reporting", body: "Accurate, timely reporting keeps people safe and helps prevent recurrence.\n\nBy the end you will be able to:\n• Tell the difference between an accident, incident and near miss\n• Record events accurately\n• Report promptly through the right channels\n• Understand what RIDDOR is" },
      { type: "slide", title: "Definitions", body: "• Accident — an unplanned event causing injury or harm (e.g. a fall causing a cut)\n• Incident — an event that could have or did cause harm (e.g. a medication error, aggression)\n• Near miss — something that could have caused harm but didn't this time\n\nAll three should be reported — near misses are early warnings." },
      { type: "slide", title: "Recording accurately", body: "When you record an event, write:\n\n• What happened, when and where\n• Who was involved and any witnesses\n• The facts — not opinions or blame\n• Any injury and action taken\n\nRecords must be legible, factual, signed and dated, and completed as soon as possible while the details are fresh." },
      { type: "slide", title: "Reporting and RIDDOR", body: "Report to your manager the same day, and record in the accident book / system.\n\nRIDDOR — the Reporting of Injuries, Diseases and Dangerous Occurrences Regulations — requires certain serious events to be reported to the Health and Safety Executive (HSE), for example specified injuries, deaths, and some work-related diseases. Your manager makes these reports, but you must report to them promptly so they can." },
      { type: "mcq", question: "A near miss (no one was harmed this time) should be:", options: ["Ignored", "Reported and recorded", "Kept quiet", "Reported only if repeated"], answer_index: 1 },
      { type: "fill_gap", text: "Records should state the ___, not opinions or blame.", answers: ["facts", "fact"] },
      { type: "drag_drop", prompt: "Match the term to its meaning.", pairs: [{ item: "Accident", match: "Event causing injury" }, { item: "Near miss", match: "Could have caused harm" }, { item: "Incident", match: "Event that did or could harm" }, { item: "RIDDOR", match: "Report serious events to HSE" }] },
      { type: "slide", title: "Summary", body: "• Report accidents, incidents AND near misses — near misses are warnings.\n• Record facts accurately: what, when, where, who, injury and action.\n• Report to your manager the same day and log it.\n• Serious events are reportable to the HSE under RIDDOR (your manager reports these).\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "A near miss should be:", options: ["Ignored", "Reported and recorded", "Hidden", "Repeated"], answer_index: 1 },
      { question: "An accident is:", options: ["A planned task", "An unplanned event causing injury or harm", "A near miss", "A meeting"], answer_index: 1 },
      { question: "Records should contain:", options: ["Opinions and blame", "The facts of what happened", "Guesses", "Nothing"], answer_index: 1 },
      { question: "You should report an accident to your manager:", options: ["Next month", "The same day", "Only if serious", "Never"], answer_index: 1 },
      { question: "RIDDOR reports go to:", options: ["The CQC only", "The Health and Safety Executive (HSE)", "The bank", "Nobody"], answer_index: 1 },
      { question: "Records should be:", options: ["Vague", "Legible, factual, signed and dated", "Anonymous", "In pencil"], answer_index: 1 },
      { question: "A medication error is best classed as:", options: ["A near miss always", "An incident to report", "Not reportable", "Trivial"], answer_index: 1 },
      { question: "Near misses matter because they are:", options: ["Unimportant", "Early warnings that prevent future harm", "Never repeated", "Someone else's job"], answer_index: 1 },
      { question: "Who usually makes RIDDOR reports?", options: ["Any carer", "The manager / responsible person", "The client", "The HSE"], answer_index: 1 },
      { question: "You should complete a record:", options: ["Weeks later", "As soon as possible while details are fresh", "Only if asked", "Never"], answer_index: 1 },
      { question: "Blaming a colleague in a record is:", options: ["Required", "Inappropriate — stick to facts", "Helpful", "Encouraged"], answer_index: 1 },
      { question: "Reporting keeps people safe by:", options: ["Hiding problems", "Helping prevent recurrence", "Wasting time", "Blaming staff"], answer_index: 1 },
    ],
  },

  {
    slug: "moving-and-handling",
    description: "Moving and handling people and objects safely to prevent injury, using the right techniques and equipment.",
    blocks: [
      { type: "slide", title: "Moving & handling", body: "Poor moving and handling causes serious injuries to staff and the people they support. Good technique and equipment prevent this.\n\nBy the end you will be able to:\n• Understand the law and risk\n• Use safe handling principles\n• Use equipment such as hoists and slide sheets\n• Recognise when NOT to move someone" },
      { type: "slide", title: "The law and risk", body: "The Manual Handling Operations Regulations 1992 require employers to avoid hazardous manual handling where possible, assess what can't be avoided, and reduce the risk.\n\nBack injuries are common and can be permanent. Always follow the person's moving and handling risk assessment and care plan — it tells you the safe method and equipment." },
      { type: "slide", title: "Safe handling principles", body: "When handling loads or supporting people:\n\n• Assess first — think before you move\n• Keep a stable base and bend your knees, not your back\n• Keep the load close to your body\n• Avoid twisting; move your feet instead\n• Never lift beyond your capability — get help or equipment\n\nNever 'drag lift' a person under the arms — it can injure them and you." },
      { type: "slide", title: "Using equipment", body: "Handling aids reduce risk:\n\n• Hoists — for people who cannot weight-bear; check the sling is the right size and correctly fitted\n• Slide sheets — to reposition in bed\n• Transfer boards, handling belts and stand aids\n\nOnly use equipment you're trained on, check it before use, and never take shortcuts. Two workers may be required — follow the care plan." },
      { type: "mcq", question: "When lifting, you should:", options: ["Bend your back and keep legs straight", "Bend your knees, keep the load close and avoid twisting", "Twist to reach", "Lift as fast as possible"], answer_index: 1 },
      { type: "fill_gap", text: "Always follow the person's moving and handling ___ assessment.", answers: ["risk"] },
      { type: "drag_drop", prompt: "Match the equipment to its use.", pairs: [{ item: "Hoist", match: "Non-weight-bearing transfer" }, { item: "Slide sheet", match: "Reposition in bed" }, { item: "Handling belt", match: "Support standing" }, { item: "Transfer board", match: "Move between surfaces" }] },
      { type: "slide", title: "Summary", body: "• Moving and handling injuries are serious and preventable.\n• The law requires avoiding, assessing and reducing manual-handling risk.\n• Assess first; bend knees not back; keep loads close; don't twist; never drag-lift.\n• Use only equipment you're trained on, check it first, and follow the care plan.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Which regulations cover manual handling?", options: ["Manual Handling Operations Regulations 1992", "COSHH", "Equality Act", "RIDDOR"], answer_index: 0 },
      { question: "When lifting you should bend your:", options: ["Back", "Knees", "Neck", "Wrists"], answer_index: 1 },
      { question: "The load should be kept:", options: ["Away from your body", "Close to your body", "Above your head", "Behind you"], answer_index: 1 },
      { question: "You should avoid:", options: ["Keeping a stable base", "Twisting your spine", "Bending your knees", "Getting help"], answer_index: 1 },
      { question: "A hoist is used for people who:", options: ["Can walk easily", "Cannot weight-bear", "Prefer it", "Are asleep"], answer_index: 1 },
      { question: "Before using handling equipment you should:", options: ["Skip checks", "Check it and be trained on it", "Improvise", "Use any sling"], answer_index: 1 },
      { question: "Dragging a person up by the arms is:", options: ["Good practice", "Unsafe and can cause injury", "Required", "Efficient"], answer_index: 1 },
      { question: "The safe method for a person is found in:", options: ["Your memory", "Their moving and handling risk assessment / care plan", "A guess", "Another client's plan"], answer_index: 1 },
      { question: "A slide sheet is used to:", options: ["Lift someone from the floor", "Reposition someone in bed", "Feed someone", "Wash someone"], answer_index: 1 },
      { question: "If a move is beyond your capability you should:", options: ["Do it anyway", "Get help or use equipment", "Skip it entirely", "Rush"], answer_index: 1 },
      { question: "Some transfers require:", options: ["One worker always", "Two workers — follow the care plan", "No workers", "The client alone"], answer_index: 1 },
      { question: "The first step before any move is to:", options: ["Lift quickly", "Assess and think it through", "Twist", "Skip the plan"], answer_index: 1 },
    ],
  },
];
