// Safeguarding — detailed module content + quiz banks.

export const safeguarding = [
  {
    slug: "safeguarding-adults-level-2",
    description: "Recognising, responding to and reporting abuse and neglect of adults at risk, under the Care Act 2014.",
    blocks: [
      { type: "slide", title: "Safeguarding adults", body: "Safeguarding means protecting an adult's right to live in safety, free from abuse and neglect. It is everyone's responsibility.\n\nBy the end you will be able to:\n• Recognise the types and signs of abuse\n• Understand who is an 'adult at risk'\n• Respond correctly to a disclosure\n• Report concerns without delay" },
      { type: "slide", title: "Who is an adult at risk?", body: "Under the Care Act 2014, an adult at risk is someone aged 18+ who:\n\n• has care and support needs, and\n• is experiencing, or at risk of, abuse or neglect, and\n• cannot protect themselves because of those needs.\n\nThe six safeguarding principles are: Empowerment, Prevention, Proportionality, Protection, Partnership and Accountability." },
      { type: "slide", title: "Types of abuse", body: "The main categories of abuse are:\n\n• Physical — hitting, restraint, misuse of medication\n• Psychological / emotional — threats, humiliation, control\n• Financial — theft, fraud, pressure over money\n• Sexual — any non-consensual sexual act\n• Neglect — failing to meet basic needs\n• Institutional / organisational — poor care culture\n• Discriminatory — abuse based on a protected characteristic\n• Domestic, modern slavery and self-neglect are also recognised." },
      { type: "slide", title: "Signs to look for", body: "Possible indicators include:\n\n• Unexplained injuries, bruising or weight loss\n• Fear, withdrawal or changes in behaviour\n• Poor hygiene, pressure sores or unmet needs\n• Missing money or possessions\n• A carer who won't leave the person alone with others\n\nSigns are not proof — but they must be reported and recorded." },
      { type: "slide", title: "Responding to a disclosure", body: "If someone discloses abuse:\n\n• Stay calm and listen — take it seriously\n• Reassure them they were right to tell you\n• Do NOT promise to keep it secret\n• Do NOT investigate or confront the alleged abuser\n• Do NOT ask leading questions\n• Record what was said in the person's own words\n• Report to your manager / safeguarding lead immediately" },
      { type: "mcq", question: "Someone discloses abuse to you. You should:", options: ["Promise to keep it secret", "Investigate it yourself", "Listen, reassure, record and report immediately", "Confront the alleged abuser"], answer_index: 2 },
      { type: "drag_drop", prompt: "Match the abuse type to an example.", pairs: [{ item: "Financial", match: "Missing money" }, { item: "Physical", match: "Unexplained bruising" }, { item: "Neglect", match: "Unmet basic needs" }, { item: "Psychological", match: "Threats and control" }] },
      { type: "slide", title: "Summary", body: "• Safeguarding protects adults at risk from abuse and neglect — it's everyone's job.\n• Know the types and signs of abuse.\n• Respond to disclosures calmly: listen, reassure, don't promise secrecy, record and report.\n• Never investigate yourself — report to your safeguarding lead immediately.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Safeguarding adults is:", options: ["Only the manager's job", "Everyone's responsibility", "Only social workers' job", "Optional"], answer_index: 1 },
      { question: "Which law defines an 'adult at risk'?", options: ["The Care Act 2014", "COSHH", "The Fire Safety Order", "The Equality Act"], answer_index: 0 },
      { question: "If someone discloses abuse, you should NOT:", options: ["Listen calmly", "Record what they said", "Promise to keep it secret", "Report it"], answer_index: 2 },
      { question: "Missing money and possessions may indicate:", options: ["Physical abuse", "Financial abuse", "Good budgeting", "Nothing"], answer_index: 1 },
      { question: "You should report a safeguarding concern:", options: ["Next week", "Immediately", "Only if proven", "Never"], answer_index: 1 },
      { question: "Which is a category of abuse?", options: ["Neglect", "Kindness", "Choice", "Independence"], answer_index: 0 },
      { question: "When someone discloses, you should record:", options: ["Your opinion", "What was said in the person's own words", "Nothing", "A summary from memory later"], answer_index: 1 },
      { question: "Should you investigate the allegation yourself?", options: ["Yes", "No — report to the safeguarding lead", "Only if you have time", "Only if asked by the client"], answer_index: 1 },
      { question: "Self-neglect is:", options: ["Not a safeguarding issue", "A recognised form of concern", "Always the person's choice", "Illegal"], answer_index: 1 },
      { question: "Signs of abuse are:", options: ["Always proof", "Indicators that must be reported and recorded", "To be ignored", "None of your concern"], answer_index: 1 },
      { question: "Asking a person leading questions during a disclosure:", options: ["Is good practice", "Should be avoided", "Helps the investigation", "Is required"], answer_index: 1 },
      { question: "Which is a safeguarding principle?", options: ["Empowerment", "Secrecy", "Delay", "Blame"], answer_index: 0 },
    ],
  },

  {
    slug: "safeguarding-children",
    description: "Recognising and reporting concerns about children and young people you may encounter in a client's home.",
    blocks: [
      { type: "slide", title: "Safeguarding children", body: "Even in adult care you may come into contact with children — in a client's home or family. Safeguarding children is everyone's responsibility.\n\nBy the end you will be able to:\n• Recognise the categories of child abuse\n• Spot signs of harm\n• Respond to a child's disclosure\n• Report concerns correctly" },
      { type: "slide", title: "Categories of abuse", body: "The four categories of child abuse are:\n\n• Physical — deliberately causing harm\n• Emotional — persistent ill-treatment affecting development\n• Sexual — involving a child in sexual activity\n• Neglect — failing to meet basic physical or emotional needs\n\nChildren can also be affected by domestic abuse, exploitation and online harm." },
      { type: "slide", title: "Recognising signs", body: "Possible signs include:\n\n• Unexplained injuries or injuries inconsistent with the explanation\n• Fearfulness, withdrawal or aggression\n• Poor hygiene, hunger or inadequate clothing\n• Age-inappropriate sexual knowledge or behaviour\n• A child left without appropriate supervision\n\nAlways consider the whole picture — and never dismiss a worry." },
      { type: "slide", title: "Responding and reporting", body: "If a child discloses or you have a concern:\n\n• Listen calmly and take it seriously\n• Do NOT promise confidentiality\n• Do NOT investigate or question the child in detail\n• Record the facts\n• Report to your safeguarding lead the same day — if a child is in immediate danger, call 999\n\nYou can also contact the NSPCC or local authority children's services." },
      { type: "mcq", question: "A child tells you something that worries you. You should:", options: ["Promise to keep it secret", "Question them in detail", "Listen, record the facts and report to your safeguarding lead", "Do nothing"], answer_index: 2 },
      { type: "fill_gap", text: "If a child is in immediate danger you should call ___.", answers: ["999"] },
      { type: "drag_drop", prompt: "Match the category to an example.", pairs: [{ item: "Neglect", match: "Hunger and poor hygiene" }, { item: "Physical", match: "Unexplained injuries" }, { item: "Emotional", match: "Persistent belittling" }, { item: "Sexual", match: "Age-inappropriate behaviour" }] },
      { type: "slide", title: "Summary", body: "• Safeguarding children is everyone's responsibility, including in adult care settings.\n• Know the four categories and the signs of harm.\n• Respond calmly, don't promise secrecy, record the facts.\n• Report to your safeguarding lead the same day; call 999 if a child is in immediate danger.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "How many main categories of child abuse are there?", options: ["Two", "Four", "Six", "Ten"], answer_index: 1 },
      { question: "Which is a category of child abuse?", options: ["Neglect", "Encouragement", "Play", "Education"], answer_index: 0 },
      { question: "If a child is in immediate danger you should:", options: ["Wait", "Call 999", "Tell no one", "Investigate first"], answer_index: 1 },
      { question: "When a child discloses you should NOT:", options: ["Listen", "Record the facts", "Promise to keep it secret", "Report it"], answer_index: 2 },
      { question: "Should you question the child in detail?", options: ["Yes", "No — leave that to trained professionals", "Only if you're curious", "Always"], answer_index: 1 },
      { question: "You may encounter children in adult care when:", options: ["Never", "Visiting a client's home or family", "Only in schools", "Only in hospitals"], answer_index: 1 },
      { question: "Concerns should be reported to your safeguarding lead:", options: ["Next month", "The same day", "Only if proven", "Never"], answer_index: 1 },
      { question: "Emotional abuse is:", options: ["A single argument", "Persistent ill-treatment affecting development", "Discipline", "Praise"], answer_index: 1 },
      { question: "Which organisation can you contact about a child concern?", options: ["The NSPCC or local children's services", "The bank", "The fire service only", "No one"], answer_index: 0 },
      { question: "A worry about a child should be:", options: ["Dismissed", "Taken seriously and acted on", "Kept quiet", "Discussed on social media"], answer_index: 1 },
      { question: "Neglect of a child looks like:", options: ["Good care", "Failing to meet basic needs", "Extra supervision", "Healthy meals"], answer_index: 1 },
      { question: "Recording a concern should include:", options: ["Your assumptions", "The facts of what you saw or were told", "Nothing", "Only opinions"], answer_index: 1 },
    ],
  },

  {
    slug: "mental-capacity-act-and-dols",
    description: "Applying the Mental Capacity Act 2005 and Deprivation of Liberty Safeguards to support decision-making.",
    blocks: [
      { type: "slide", title: "The Mental Capacity Act 2005", body: "The Mental Capacity Act (MCA) protects and empowers people aged 16+ who may lack capacity to make some decisions.\n\nBy the end you will be able to:\n• State the five statutory principles\n• Understand how capacity is assessed\n• Support decision-making\n• Recognise what Deprivation of Liberty Safeguards (DoLS) are for" },
      { type: "slide", title: "The five principles", body: "1. Assume capacity unless proven otherwise\n2. Support people to make their own decisions before concluding they can't\n3. People can make unwise decisions — that alone doesn't mean they lack capacity\n4. Any decision made for someone must be in their best interests\n5. Choose the option that is least restrictive of their rights and freedom" },
      { type: "slide", title: "Assessing capacity", body: "Capacity is decision-specific and time-specific. A person has capacity if they can:\n\n1. Understand the information relevant to the decision\n2. Retain it long enough to decide\n3. Weigh it up\n4. Communicate their decision (by any means)\n\nIf they cannot do one or more of these because of an impairment of mind or brain, they may lack capacity for that decision." },
      { type: "slide", title: "Best interests and DoLS", body: "If someone lacks capacity for a decision, a 'best interests' decision is made — involving the person as far as possible, their wishes, and those who know them.\n\nDeprivation of Liberty Safeguards (DoLS) apply when a person who lacks capacity is under continuous supervision and control and not free to leave, in a care home or hospital. DoLS ensure this is lawful, necessary and reviewed." },
      { type: "mcq", question: "Under the MCA, you must always start by assuming that a person:", options: ["Lacks capacity", "Has capacity", "Needs a best-interests decision", "Cannot decide anything"], answer_index: 1 },
      { type: "fill_gap", text: "Capacity is assessed for each specific ___, not overall.", answers: ["decision"] },
      { type: "drag_drop", prompt: "Match the MCA principle to its meaning.", pairs: [{ item: "Assume capacity", match: "Until proven otherwise" }, { item: "Support decisions", match: "Help before concluding they can't" }, { item: "Unwise choices", match: "Allowed with capacity" }, { item: "Least restrictive", match: "Protect freedom" }] },
      { type: "slide", title: "Summary", body: "• The MCA empowers people to make their own decisions and protects those who can't.\n• Assume capacity; support decision-making; unwise choices are allowed.\n• Capacity is decision- and time-specific and assessed in four steps.\n• Best-interests decisions must be least restrictive; DoLS make any deprivation of liberty lawful.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "The MCA says you must start by assuming a person:", options: ["Lacks capacity", "Has capacity", "Is confused", "Needs DoLS"], answer_index: 1 },
      { question: "Capacity is:", options: ["The same for all decisions", "Decision- and time-specific", "Permanent once lost", "Only for over-65s"], answer_index: 1 },
      { question: "A person with capacity who makes an unwise choice:", options: ["Lacks capacity", "Still has the right to make it", "Must be overruled", "Should be reported"], answer_index: 1 },
      { question: "A best-interests decision must be:", options: ["The cheapest", "The least restrictive of rights", "The carer's preference", "The quickest"], answer_index: 1 },
      { question: "Which is one of the four parts of assessing capacity?", options: ["Understand the information", "Be over 65", "Have a diagnosis", "Agree with the carer"], answer_index: 0 },
      { question: "DoLS apply when someone lacking capacity is:", options: ["Free to leave", "Under continuous supervision and not free to leave", "At home alone", "Fully independent"], answer_index: 1 },
      { question: "The MCA applies to people aged:", options: ["16 and over", "Only 18+", "Only 65+", "Any age"], answer_index: 0 },
      { question: "Supporting decision-making means:", options: ["Deciding for the person", "Helping them decide before concluding they can't", "Ignoring them", "Rushing them"], answer_index: 1 },
      { question: "Who should be involved in a best-interests decision?", options: ["Only the carer", "The person as far as possible and those who know them", "No one", "The manager alone"], answer_index: 1 },
      { question: "Lacking capacity for one decision means:", options: ["The person lacks capacity for all decisions", "It applies only to that decision", "They should be sedated", "Nothing"], answer_index: 1 },
      { question: "The 'least restrictive' principle protects a person's:", options: ["Money", "Rights and freedom", "Diet", "Schedule"], answer_index: 1 },
      { question: "DoLS exist to ensure a deprivation of liberty is:", options: ["Hidden", "Lawful, necessary and reviewed", "Permanent", "Ignored"], answer_index: 1 },
    ],
  },

  {
    slug: "whistleblowing",
    description: "Raising concerns about wrongdoing or unsafe practice safely, and your legal protection when you do.",
    blocks: [
      { type: "slide", title: "What is whistleblowing?", body: "Whistleblowing is raising a concern about wrongdoing, danger or malpractice at work that affects others.\n\nBy the end you will be able to:\n• Explain what whistleblowing is\n• Recognise concerns that should be raised\n• Know how to raise a concern\n• Understand your legal protection" },
      { type: "slide", title: "When to blow the whistle", body: "Raise a concern if you see, for example:\n\n• Abuse or neglect of the people you support\n• Unsafe practice or covering up mistakes\n• Fraud or theft\n• Health and safety risks\n• Breaches of policy that put people at risk\n\nIf in doubt, raise it — it's better to be safe." },
      { type: "slide", title: "How to raise a concern", body: "1. Raise it internally first — with your manager or the named person in your whistleblowing policy\n2. If it isn't dealt with, escalate to a senior leader\n3. If still unresolved, contact an external body — e.g. the CQC or the charity Protect\n\nRecord what you reported, to whom and when. Concerns should be acted on, not ignored." },
      { type: "slide", title: "Your protection", body: "The Public Interest Disclosure Act 1998 protects workers who raise genuine concerns in the public interest from being dismissed or victimised.\n\nYou do not need to prove the wrongdoing — you only need a reasonable belief. Raising a concern honestly means you are protected, even if you turn out to be mistaken." },
      { type: "mcq", question: "You witness a colleague being rough with a client. You should:", options: ["Ignore it — it's not your business", "Confront them alone", "Raise a concern through your whistleblowing policy", "Wait to see if it happens again"], answer_index: 2 },
      { type: "fill_gap", text: "You should usually raise a concern ___ first, with your manager.", answers: ["internally"] },
      { type: "drag_drop", prompt: "Order the escalation steps (match step to stage).", pairs: [{ item: "Step 1", match: "Tell your manager" }, { item: "Step 2", match: "Escalate to a senior leader" }, { item: "Step 3", match: "Contact CQC or Protect" }, { item: "Always", match: "Record it" }] },
      { type: "slide", title: "Summary", body: "• Whistleblowing means raising concerns about wrongdoing or danger.\n• Raise concerns about abuse, unsafe practice, fraud or risk — if in doubt, raise it.\n• Go internal first, then escalate; record what you did.\n• You're legally protected when you raise a genuine concern in good faith.\n\nComplete the assessment to earn your certificate." },
    ],
    questions: [
      { question: "Whistleblowing is:", options: ["Gossiping", "Raising a concern about wrongdoing or danger", "Making a formal complaint about your pay", "Reporting a colleague you dislike"], answer_index: 1 },
      { question: "You should usually raise a concern first:", options: ["To the newspaper", "Internally with your manager", "On social media", "Nowhere"], answer_index: 1 },
      { question: "Which law protects whistleblowers?", options: ["Public Interest Disclosure Act 1998", "COSHH", "Equality Act 2010", "Fire Safety Order"], answer_index: 0 },
      { question: "To be protected, you must:", options: ["Prove the wrongdoing", "Have a reasonable belief and act in good faith", "Be a manager", "Stay anonymous"], answer_index: 1 },
      { question: "If your concern isn't dealt with internally you can:", options: ["Give up", "Escalate, and contact an external body like CQC", "Ignore it", "Take revenge"], answer_index: 1 },
      { question: "Seeing abuse of a client, you should:", options: ["Ignore it", "Raise a concern", "Confront the abuser alone", "Wait"], answer_index: 1 },
      { question: "If in doubt about whether to raise a concern:", options: ["Stay quiet", "Raise it — better to be safe", "Ask the person you're worried about", "Wait a year"], answer_index: 1 },
      { question: "You should record:", options: ["Nothing", "What you reported, to whom and when", "Only good news", "Your feelings only"], answer_index: 1 },
      { question: "Whistleblowing concerns include:", options: ["Unsafe practice and fraud", "A colleague's haircut", "The weather", "Menu choices"], answer_index: 0 },
      { question: "A worker who raises a genuine concern can be:", options: ["Dismissed for it lawfully", "Protected from dismissal and victimisation", "Ignored legally", "Punished"], answer_index: 1 },
      { question: "An external body you could contact is:", options: ["The CQC", "Your bank", "A supermarket", "None"], answer_index: 0 },
      { question: "Covering up a mistake that put someone at risk is:", options: ["Acceptable", "A concern that should be raised", "None of your business", "Good teamwork"], answer_index: 1 },
    ],
  },
];
